site_name: Franjo's documentation
site_description: Go & Python code project documentation
site_url: https://sandbox.unizd.hr/profesor00/documentation/site/
theme: material
markdown_extensions:
  - toc
  - extra
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:  # <-- here!
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - "Home": "index.md"
    - "About": "about.md"
    - "Section 1":
      - "Section 1 Page 1": "section-01/page-01.md"
    - "Section 2":
      - "Section 2 Page 1": "section-02/page-01.md"
